// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pesaarhgrfixyaoillce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlc2FhcmhncmZpeHlhb2lsbGNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDA2MjMsImV4cCI6MjA2OTM3NjYyM30.X5Wt1Tec9gHh8HWMdgz6QA3N7DWBNys9fyEuLWFCCx4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});